### ISSUE TITLE
Could you please share more webpage data sets or the Dataset-Builder in your Master's thesis?

### ISSUE THREAD

**Issue by fhyme** [rkrzr/dataset-random#1]
Dear Robert,
Thanks for your open source spirit to share the webpage data set[1, 2] used in your Master's thesis ("A Quantitative Comparison of Semantic Web Page Segmentation Algorithms").
Recently, I'm doing a similar study on Web Page Segmentation and need more web pages with manually marked up semantic blocks. Could you please  open more webpage data with semantic blocks or could you please open the source code of the Dataset-Builder mentioned in your paper? Thus I can build my dataset in local and I'll also open my dataset after experiment.

Looking forward to your reply.

[1] https://github.com/rkrzr/dataset-popular
[2] https://github.com/rkrzr/dataset-random

**Comment by TomRaz** [comment]
@rkrzr thank you for this great dataset!
It will also extremely help me if you can open source the dataset builder.

**Comment by rkrzr** [comment]
Hi @TomRaz, it's nice to see that this dataset is useful to you. I have a related dataset of popular websites over here: https://github.com/rkrzr/dataset-popular

I unfortunately no longer have the code of the dataset builder (it's been too long ago that I wrote my thesis). I remember that it was a fairly simple Javascript program that I wrote, that you could activate for the currently opened page in the browser by clicking on a bookmark icon.

The builder basically worked like this:

1. It added a box outline over the HTML element that you were hovering over
2. It allowed you to "widen" the box by clicking a button (this simply selected the parent element of the current element)
3. You could widen as many times until you found the right level of abstraction
4. You could press another button, which would add a CSS class to the selected element to mark it as a page segment
5. Finally, after adding all boxes, you could press a button to serialize the DOM to disk

I hope this explanation helps, even though I no longer have the original code.

**Comment by TomRaz** [comment]
@rkrzr Thank you, this was very helpful!
